CMSIS_MCU = RA4W1
MCU_SERIES = m4
LD_FILES = boards/EK_RA4W1/ra4w1_ek.ld

# MicroPython settings
MICROPY_VFS_FAT = 1

CFLAGS+=-DDEFAULT_DBG_CH=0 \
          -DCFG_TUD_MAX_SPEED=OPT_MODE_FULL_SPEED \
          -DCFG_TUSB_RHPORT0_MODE=OPT_MODE_DEVICE
          